### ISSUE TITLE
Error when using Image.scaled, QImage Api mismatch.

### ISSUE THREAD

**Issue by roya0045** [Kanahiro/MagicWand#13]
Hi there,

Just wanted to let you know that you may want to update [this line](https://github.com/Kanahiro/MagicWand/blob/ef74e00bfe6c3254254d2073f46486099aec9234/image_analyzer.py#L29)

The API for QImage seems different now, at least incomptaible with that line (see https://doc.qt.io/qt-6/qimage.html#scaled-1 ) as current QGIS build should be compliant with Qt6 and an error is thrown with 3.27.

A simple fix would be to change it for `scaled_img = image.scaled(int(image.width() * resize_multiply), int(image.height() * resize_multiply))`

Thanks,

**Comment by roya0045** [comment]
@Kanahiro I can propose it as a PR if you want, or I can let you update the plugin at your conveiniance.

Thanks for the great work btw.

**Comment by Kanahiro** [comment]
Hi @roya0045 , thanks to a great feedback!
I've just written a patch you suggested ?
Could you check this? I confirm this works QGIS3.22 on macOS but don't have Qt6 environment...

**Comment by roya0045** [comment]
> Hi @roya0045 , thanks to a great feedback! I've just written a patch you suggested ? Could you check this? I confirm this works QGIS3.22 on macOS but don't have Qt6 environment...

The latest qgis version is made to be compatible with qt6 but is still on 5.something, The fix worked for me in 3.27, it should work for others too. Thanks!
